/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;


import Apliacion.Control;
import DTOs.UsuarioDTO;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author HP
 */
public class AgregarUsuario extends javax.swing.JPanel {
private Control control;
private boolean isAdmin;
    /**
     * Creates new form AgregarTutor
     */
    public AgregarUsuario(Control control, boolean isAdmin) {
        this.control = control;
        this.isAdmin = isAdmin;
        initComponents();
        valoresDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoContrasenia = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnConfirmar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        boxCorreo = new javax.swing.JComboBox<>();
        campoApellidoP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoContrasenia2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkAdmin = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(829, 645));
        setMinimumSize(new java.awt.Dimension(829, 645));
        setPreferredSize(new java.awt.Dimension(829, 645));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("E-mail:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Paterno");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 60, -1));

        campoContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 240, -1));

        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 400, -1));

        campoApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 240, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Registrar Usuario");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 290, 70));

        BtnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        BtnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(204, 204, 204));
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmarMouseClicked(evt);
            }
        });
        add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Contrasenia:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        campoEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 180, -1));

        boxCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boxCorreo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@outlook.es", "@hotmail.com" }));
        add(boxCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        campoApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 240, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Materno");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Apellidos:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        campoContrasenia2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campoContrasenia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 240, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Confirmar contrasenia:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        checkAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkAdmin.setText("Hacer Administrador?");
        add(checkAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        // TODO add your handling code here:
        control.mostrarLogIn();
    }//GEN-LAST:event_BtnCancelarMouseClicked

    private void BtnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmarMouseClicked
        // TODO add your handling code here:
        if(campoContrasenia.getText().equals(campoContrasenia2.getText())) crearUsuario();
        else JOptionPane.showMessageDialog(null,"Las contrasenias no coinceden","Error", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_BtnConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JComboBox<String> boxCorreo;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoContrasenia;
    private javax.swing.JTextField campoContrasenia2;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JCheckBox checkAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables


    public void valoresDefault(){
        checkAdmin.setEnabled(isAdmin);
        checkAdmin.setVisible(isAdmin);
        campoEmail.addKeyListener(new java.awt.event.KeyAdapter()
       {
       @Override
       public void keyTyped(KeyEvent e){
           char c = e.getKeyChar();
           if(campoEmail.getText().length() >= 20){
               e.consume();
           }
       }
    });
        campoContrasenia.addKeyListener(new java.awt.event.KeyAdapter()
       {
       @Override
       public void keyTyped(KeyEvent e){
//           char c = e.getKeyChar();
//           if(!Character.isDigit(c)){
//               e.consume();
//               Toolkit.getDefaultToolkit().beep();
//           }
           if(campoContrasenia.getText().length() >= 9){
               e.consume();
               Toolkit.getDefaultToolkit().beep();
               
           }
       }
    });
    }
    
    public void crearUsuario(){
        UsuarioDTO usuario = new UsuarioDTO();
        usuario.setNombre(campoNombre.getText());
        usuario.setApellidoP(campoApellidoP.getText());
        usuario.setApellidoM(campoApellidoM.getText());
        usuario.setCorreo(campoEmail.getText() + boxCorreo.getSelectedItem().toString());
        usuario.setContrasenia(campoContrasenia.getText());
        if(checkAdmin.isSelected()) usuario.setTipoUsuario("Administrador");
        
        if(control.agregarUsuario(usuario) ==null){
            JOptionPane.showMessageDialog(null,"usuario nulo","Error", JOptionPane.ERROR_MESSAGE);
        }else{
            control.mostrarAdministracionUsuarios();
        }
    }

}
