/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Administrador;

import Apliacion.Control;
import DTOs.UsuarioDTO;
import java.awt.Color;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.bson.types.ObjectId;

/**
 *
 * @author HP
 */
public class AdminUsuarios extends javax.swing.JPanel {
    private Control control;
    private ObjectId _id;
    
    /**
     * Creates new form MenuUsuarios
     */
    public AdminUsuarios(Control control) {
        this.control = control;
        initComponents();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmpoBuscr = new javax.swing.JTextField();
        lbltitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar1 = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        BtnActualizar1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setMaximumSize(new java.awt.Dimension(963, 688));
        setMinimumSize(new java.awt.Dimension(963, 688));
        setPreferredSize(new java.awt.Dimension(963, 688));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(cmpoBuscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 580, 40));

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltitulo.setText("Administracion de usuarios");
        add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("puedes buscar por id o nombre de usuario");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 270, 20));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 880, 410));

        BtnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        BtnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(204, 204, 204));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, -1, -1));

        BtnEliminar1.setBackground(new java.awt.Color(0, 0, 0));
        BtnEliminar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnEliminar1.setForeground(new java.awt.Color(204, 204, 204));
        BtnEliminar1.setText("Eliminar");
        BtnEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminar1MouseClicked(evt);
            }
        });
        add(BtnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        BtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(204, 204, 204));
        BtnAgregar.setText("Agregar");
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, -1));

        BtnActualizar1.setBackground(new java.awt.Color(0, 0, 0));
        BtnActualizar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnActualizar1.setForeground(new java.awt.Color(204, 204, 204));
        BtnActualizar1.setText("Ver informacion");
        BtnActualizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizar1MouseClicked(evt);
            }
        });
        add(BtnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked
        // TODO add your handling code here:
//        if(tblUsuarios.getSelectedRow() != -1 ){
//            control.mostrarActulizarAlumno();
//        }else{
//            JOptionPane.showMessageDialog(
//                null,
//                "Seleccione a un alumno antes de querer actualizarlo",
//                "Error",
//                JOptionPane.ERROR_MESSAGE
//            );
//        }

    }//GEN-LAST:event_BtnActualizarMouseClicked

    private void BtnEliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminar1MouseClicked
        // TODO add your handling code here:
//        if(control.eliminarAlumno(control.getAlumnoTemporal().get_id())){
//            JOptionPane.showMessageDialog(
//                null,
//                "El alumno fue eliminado correctamente",
//                "Exito",
//                JOptionPane.INFORMATION_MESSAGE
//            );
//            control.mostrarMenuAlumnos();
//        }else{
//            JOptionPane.showMessageDialog(
//                null,
//                "No se puedo eliminar al alumno",
//                "Error",
//                JOptionPane.ERROR_MESSAGE
//            );
//        }
    control.eliminarUsuario(this._id);

    }//GEN-LAST:event_BtnEliminar1MouseClicked

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        // TODO add your handling code here:
        control.mostrarAgregarUsuario(true);
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void BtnActualizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizar1MouseClicked

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        obtenerUsuarioSeleccionado();
    }//GEN-LAST:event_tblUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnActualizar1;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar1;
    private javax.swing.JTextField cmpoBuscr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables


    public void obtenerUsuarioSeleccionado(){
        int filaSeleccionada = tblUsuarios.getSelectedRow();
        if(filaSeleccionada != -1){
            int modelRow = tblUsuarios.convertRowIndexToModel(filaSeleccionada);
            UsuarioDTO user = control.buscarUsuariosPorNombre(cmpoBuscr.getText()).get(modelRow);
            this._id = user.get_id();
        }
    }
        
    public void CargarTabla(){
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Correo"},0
        )
         {
        @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        model.setRowCount(0);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblUsuarios.setRowSorter(sorter);
        for (UsuarioDTO user : control.consultarTodosUsuarios()) {
            Object[] fila = new Object[]{
                user.getNombre(),
                user.getApellidoP(),
                user.getApellidoM(),
                user.getCorreo(),
                };
            model.addRow(fila);
        } 
       tblUsuarios.setModel(model);
        
        tblUsuarios.setRowSelectionAllowed(true);
        tblUsuarios.setColumnSelectionAllowed(false);  
        tblUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUsuarios.getTableHeader().setReorderingAllowed(false);
        tblUsuarios.getTableHeader().setResizingAllowed(false);
        tblUsuarios.setSelectionBackground(Color.CYAN);
        tblUsuarios.setSelectionForeground(Color.BLACK);

    }
}
