/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Administrador;

import java.awt.Color;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class MenuUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form MenuUsuarios
     */
    public MenuUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmpoBuscr = new javax.swing.JTextField();
        lbltitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(cmpoBuscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 580, 40));

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltitulo.setText("Administracion de usuarios");
        add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("puedes buscar por id o nombre de usuario");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 270, 20));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 770, 410));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cmpoBuscr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables


    public void CargarTabla(){
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Esceuela Procedencia", "Grado Escolar", "Teléfono","Edad"},0
        )
         {
        @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        model.setRowCount(0);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblUsuarios.setRowSorter(sorter);
//        for (Producto alumno : control.consultarAlumnos()) {
// flt metodos control
//            Object[] fila = new Object[]{
//                alumno.getId(),
//                alumno.getNombre(),
//                alumno.getApellidoPaterno(),
//                alumno.getApellidoMaterno(),
//                alumno.getEscuela_Procedencia(),
//                alumno.getGrado_Escolar(),
//                alumno.getTelefono(),
//                alumno.getEdad()
//                };
//            model.addRow(fila);
//        }
        tblUsuarios.setModel(model);
        
        tblUsuarios.setRowSelectionAllowed(true);
        tblUsuarios.setColumnSelectionAllowed(false);  
        tblUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUsuarios.getTableHeader().setReorderingAllowed(false);
        tblUsuarios.getTableHeader().setResizingAllowed(false);
        tblUsuarios.setSelectionBackground(Color.CYAN);
        tblUsuarios.setSelectionForeground(Color.BLACK);

    }
}
