/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Administrador;

import Apliacion.Control;
import DTOs.UsuarioDTO;

/**
 *
 * @author HP
 */
public class PanelLogIn extends javax.swing.JPanel {
    
private Control control;
    /**
     * Creates new form PanelLogIn
     */
    public PanelLogIn(Control control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoPassword = new javax.swing.JTextField();
        campoUsuario = new javax.swing.JTextField();
        BtnLogIn = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(520, 700));
        setMinimumSize(new java.awt.Dimension(520, 700));
        setPreferredSize(new java.awt.Dimension(520, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Volatus");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("contrasenhia");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Correo Electronico");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));
        add(campoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 320, 40));
        add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 320, 40));

        BtnLogIn.setBackground(new java.awt.Color(0, 0, 0));
        BtnLogIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogIn.setText("Iniciar Sesion");
        BtnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogInMouseClicked(evt);
            }
        });
        add(BtnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 180, 40));

        BtnRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnRegistro.setText("Registrarse");
        BtnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistroMouseClicked(evt);
            }
        });
        add(BtnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogInMouseClicked
        // TODO add your handling code here:
        autenticacion();
    }//GEN-LAST:event_BtnLogInMouseClicked

    private void BtnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistroMouseClicked
        // TODO add your handling code here:
        
       control.mostrarAgregarUsuario(false);
    }//GEN-LAST:event_BtnRegistroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogIn;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JTextField campoPassword;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void autenticacion(){
        if(control.signIn(campoUsuario.getText(), campoPassword.getText())){
            UsuarioDTO us = control.getUsuarioDTO();
            if("usuario".equals(us.getTipoUsuario())){
                control.mostrarMenuUsuario();
            }else{
                control.mostrarPanelAdministrador();
            }
        }
    }
}
